### ISSUE TITLE
Some personal thoughts about RXD mod. Sorry for any offence

### ISSUE THREAD

**Issue by kal6legend** [RifsxD/RXD-MODPACK-PROJ#11]
I like this mod, but I am still used to the original icon aiming. Do you want the author to change it?, And I don't insist,。，
，。
In addition, the mod of the PC gun sound of the website is still version 8.10. Could you update it
![Screenshot_2022-06-12-23-20-01-52_439a3fec0400f8974d35eed09a31f914](https://user-images.githubusercontent.com/107359161/173240461-bfe2a070-75da-4a76-9d62-90a07bd8626b.jpg)

**Comment by kal6legend** [comment]
After I hit mod, I entered the game with m41d. As a result, I couldn't play the game normally. He flashed back. It should be the problem in the 3D folder

**Comment by rifsxd** [comment]
I don't underdstand your problem and your english, and this repo is about rxd modpack that contains all the mods, so pc guns will be updated separately later and reporting other outdated mods here is irrelevant.
