### ISSUE TITLE
No sound when install android mod

### ISSUE THREAD

**Issue by chadd1412** [RifsxD/RXD-MODPACK-PROJ#13]
When i install the mod my wot blitz just lost sound all of it even ads. I like your mod but it to much error even i try to add it in my steam

**Comment by rifsxd** [comment]
you havent installed the modpack properly, the modpack has 0 bugs tested multiple times by everyone, make sure you install the modpack in a clean game without 3rd party mods installed, for android backup the game data then uninstall teh stock apk then install rxd mod apk now copy back the backed up data and now copy paste the modpack data, after that install the dlc patch and now you are set to go, additional info - android modpack will be available for auto installation through ForBlitz App. And about your steam problem its better to just install it through my auto installer and then install the dlc patch manually and you are good to go, and for more help and FAQ guide join our discord server there are detailed instructions and support by moderator.
