### ISSUE TITLE
Bug, installed the last fix, hits on the tank are still not audible

### ISSUE THREAD

**Issue by baleraka** [RifsxD/RXD-MODPACK-PROJ#21]
Bug, installed the last fix, hits on the tank are still not audible

**Comment by rifsxd** [comment]
android specific issue - android cant handle the bitrate of the hits sounds

**Comment by baleraka** [comment]
I'm playing on the computer

**Comment by rifsxd** [comment]
its not an issue on pc as i play it daily and others too, if its a problem on your side then try settings the bitrate of the sound device to 48000Hz

**Comment by rifsxd** [comment]
upload a video for me to inspect your problem

**Comment by baleraka** [comment]
https://www.youtube.com/watch?v=HzqQG-El9FM&ab_channel=MolodouSushnak

**Comment by baleraka** [comment]
no sounds of a recochet hitting a tank

**Comment by rifsxd** [comment]
> https://www.youtube.com/watch?v=HzqQG-El9FM&ab_channel=MolodouSushnak

this is not my modpack

**Comment by rifsxd** [comment]
thats dp's modpack, install my modpack clean

**Comment by rifsxd** [comment]
> no sounds of a recochet hitting a tank

you are using dp's ,qirashi's and mine all at the same time so it will be bugged
