### ISSUE TITLE
What is the problem with flattery, if steam is already ready, then only exe is needed for flattery? I can provide exe from lesta

### ISSUE THREAD

**Issue by baleraka** [RifsxD/RXD-MODPACK-PROJ#23]
What is the problem with flattery, if steam is already ready, then only exe is needed for flattery? I can provide exe from lesta

**Comment by baleraka** [comment]
exe already patched

**Comment by rifsxd** [comment]
i can patch it myself but i need the exe file for lesta since in dont play on lesta, do something give me the patched lesta blitz exe so i can push the update for lesta faster

**Comment by baleraka** [comment]
https://drive.google.com/file/d/1j1FZXtVsGpZHF-5FTI2sSUJO-Q_q3xio/view?usp=share_link

Of course, take it bro, it's already patched exe (I took it from kyurashi)

**Comment by rifsxd** [comment]
and also the stock non patched one too

**Comment by baleraka** [comment]
Жду мод пак для русских)))))

**Comment by baleraka** [comment]
https://drive.google.com/file/d/1XNEwQKITEhX3Sz9U98OgI3SWoD7UFJfM/view?usp=share_link  ( no path)

**Comment by rifsxd** [comment]
> Жду мод пак для русских)))))

coming in about an hour

**Comment by rifsxd** [comment]
updated

**Comment by baleraka** [comment]
Can you give purely friendly files, without an installer?

**Comment by rifsxd** [comment]
why?

**Comment by baleraka** [comment]
Okay, I found a manual installation, now tell me what is the password for the archive?

**Comment by rifsxd** [comment]
but why do you want the manual tho?

**Comment by baleraka** [comment]
I don't need a manual, you have passwords for the archive and for the auto-installer

**Comment by baleraka** [comment]
![image](https://user-images.githubusercontent.com/117670627/201147370-6a1f4c10-c4ce-4e4b-8a26-c7f29cf208b3.png)

**Comment by baleraka** [comment]
![image](https://user-images.githubusercontent.com/117670627/201147459-7686aed6-4c19-41ad-8949-137cf2dd97b7.png)

**Comment by rifsxd** [comment]
yes use the auto installer and then look for a red widget in the webpage that says where you will get the password

**Comment by baleraka** [comment]
thx

**Comment by rifsxd** [comment]
found it?

**Comment by baleraka** [comment]
Да спасибо!!1
