### ISSUE TITLE
About bugs in the game

### ISSUE THREAD

**Issue by kal6legend** [RifsxD/RXD-MODPACK-PROJ#24]
![jj](https://user-images.githubusercontent.com/107359161/202853298-07260a8b-0325-445c-b481-bd835d311635.PNG)
![b](https://user-images.githubusercontent.com/107359161/202853455-58fd10ad-64f1-48ae-8511-3430937d4a38.PNG)

**Comment by rifsxd** [comment]
install the modpack properly as stated in the readme.txt guide or video guide in my youtube channel
