### ISSUE TITLE
Asking for WG Client mod version

### ISSUE THREAD

**Issue by ghost** [RifsxD/RXD-MODPACK-PROJ#25]
Hey do you have the mod pack for WGC yet, it's been a week since you published the new version and there wasn't an WGC mod pack yet (srry if my English isn't that great)

**Comment by rifsxd** [comment]
provide me the latest stock wotblitz.exe from the wg client and i will do the modpack

**Comment by ghost** [comment]
https://drive.google.com/file/d/1jnsC0vjxTzU-Hgd7jb08zD7u9OLbHaMB/view?usp=share_link
Here you go, keep up the good work!

**Comment by rifsxd** [comment]
Released.
