### ISSUE TITLE
How do I actually remove this from my Blitz?

### ISSUE THREAD

**Issue by xWass** [RifsxD/RXD-MODPACK-PROJ#26]
Ive uninstalled this from the programs and features part of settings, uninstalled and reinstalled blitz, and for whatever reason its still here. How do i get rid of it? Playing through Steam

**Comment by xWass** [comment]
Also, my game is consistently crashing. Not sure what tank is triggering it, but its eating shit every time i play with them

**Comment by kal6legend** [comment]
I think we need to wait for the relevant version 9.5

**Comment by rifsxd** [comment]
Update released for 9.5.0
