### ISSUE TITLE
[v9.0 Modpack] Observation is weird when rotating mouse

### ISSUE THREAD

**Issue by mwdotzom** [RifsxD/RXD-MODPACK-PROJ#9]
Problem: 
  1. The normal observation view behaves strangely. Specifically, the viewing range is not following the mouse cursor as it should be, but rather like "following the rotation of the turret". If the mouse moves faster than that, the view is going to "jump" after the described slow rotation, making the game view pretty wrecked and unplayable.
  2. The crew voice sounds distant and inaudible. ( ingame music volumn set to 30)

What I did: 
  1. Uninstalled old WOTB from Steam
  3. Deleted remaining folder of WOTB in Steam directory
  4. Fresh installed WOTB v9.0
  5. Installed RXD-Modpack (both automatic and manual attempted)
  6. Enter game

My system info:
---
Processor	AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz
Installed RAM	16.0 GB (15.4 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Pro
Version	21H2
Installed on	‎24/‎10/‎2021
OS build	22000.675
Experience	Windows Feature Experience Pack 1000.22000.675.0
---

**Comment by mwdotzom** [comment]
Update: I tried the new Microsoft Store client patch, went through the tutorial, and everything works perfectly, neither of the above appears, so I guess it's something to do with Steam

**Comment by rifsxd** [comment]
> Update: I tried the new Microsoft Store client patch, went through the tutorial, and everything works perfectly, neither of the above appears, so I guess it's something to do with Steam

Steam shouldnt have any problems as i play on steam myself and tested multiple times and made videos, tho probably a big on the game itself on steam i guess, let me know if that happens when you are completely stock without mods installed, and for the crew voice volume - below 49 is male and going below will decrease the male volume & above 51 is female increasing the volume will decrease the female crew. Thanks for the report i will check on the weird issue youve been facing, for more help join our discord server for indepth visual help.

**Comment by mwdotzom** [comment]
Update: I discovered that even the original steam client on my laptop has the same issue. Thus it's clear that my steam broke rather then the mod. I'm contacting WG for technical support on this

**Comment by rifsxd** [comment]
> Update: I discovered that even the original steam client on my laptop has the same issue. Thus it's clear that my steam broke rather then the mod. I'm contacting WG for technical support on this



> Update: I discovered that even the original steam client on my laptop has the same issue. Thus it's clear that my steam broke rather then the mod. I'm contacting WG for technical support on this

i think its probably WG's new aiming mechanic conflicting with my Fps unlock mod you might be using cuz WG recently cleared it up as the new system wasnt meant to be used fps more than 120

**Comment by mwdotzom** [comment]
> > Update: I discovered that even the original steam client on my laptop has the same issue. Thus it's clear that my steam broke rather then the mod. I'm contacting WG for technical support on this
> 
> > Update: I discovered that even the original steam client on my laptop has the same issue. Thus it's clear that my steam broke rather then the mod. I'm contacting WG for technical support on this
> 
> i think its probably WG's new aiming mechanic conflicting with my Fps unlock mod you might be using cuz WG recently cleared it up as the new system wasnt meant to be used fps more than 120

Yes you are right, I forgot that I installed the FPS unlock mod. Do you know how to uninstall that? I tried deleting the 3 files in DAVAProject folder, but still no luck. Both Steam and WG.net original clients still have the same issue, and I can only stick to MS client for now.

**Comment by rifsxd** [comment]
Revert back the files to stock from data folder that you copy pasted
